version: '3.8'
name: Project_Template

services:
  # Nginx reverse proxy with SSL termination
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - auth-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.frontend
      args:
        FRONTEND_PORT: ${FRONTEND_PORT}
    expose:
      - "${FRONTEND_PORT}"
    extra_hosts:
      - "template-app.dev:host-gateway"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      # Env kind
      - FRONT_ENV=${FRONT_ENV}

      # API url
      - BACKEND_URL=http://backend:${BACKEND_API_PORT}${BACKEND_API_DEFAULT_ROUTE}
    depends_on:
      - backend
    networks:
      - auth-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.backend
      args:
        BACKEND_API_PORT: ${BACKEND_API_PORT}
        BACKEND_API_HOST: ${BACKEND_API_HOST}
    expose:
      - "${BACKEND_API_PORT}"
    extra_hosts:
      - "template-app.dev:host-gateway"
    volumes:
      - ../backend/src:/app
    environment:
      ##### Env kind
      - API_ENV=${API_ENV}

      - UVICORN_WORKERS=1

      ##### Auth systems
      # Activated auth systems
      - AUTH_EMAIL_PASSWORD=${AUTH_EMAIL_PASSWORD}
      - AUTH_MICROSOFT=${AUTH_MICROSOFT}
      - AUTH_GOOGLE=${AUTH_GOOGLE}
      - AUTH_FACEBOOK=${AUTH_FACEBOOK}
      - AUTH_STRAVA=${AUTH_STRAVA}

      # Backend API info
      - BACKEND_API_HOST=${BACKEND_API_HOST}
      - BACKEND_API_PORT=${BACKEND_API_PORT}
      - BACKEND_API_DEFAULT_ROUTE=${BACKEND_API_DEFAULT_ROUTE}

      # Microsoft Entra ID
      - ENTRA_ID_CLIENT_ID=${ENTRA_ID_CLIENT_ID}
      - ENTRA_ID_CLIENT_SECRET=${ENTRA_ID_CLIENT_SECRET}
      - ENTRA_ID_TENANT_ID=${ENTRA_ID_TENANT_ID}

      # Google
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

      # Facebook
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}

      # Strava
      - STRAVA_CLIENT_ID=${STRAVA_CLIENT_ID}
      - STRAVA_CLIENT_SECRET=${STRAVA_CLIENT_SECRET}

      # JWT Configuration
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

      ##### Database
      # Database info
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=database
      - DATABASE_PORT=${DATABASE_PORT}
    depends_on:
      - database
    networks:
      - auth-network

  database:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge

volumes:
  postgres_data:
